# docker-compose.yml
version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/AsyncCQRSProcess/postgres:/var/lib/postgresql/data
      - ~/AsyncCQRSProcess/src/migrations/create_orders.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_USER=test_user
      - POSTGRES_DB=orders_db
    networks:
      - async_net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/AsyncCQRSProcess/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/AsyncCQRSProcess/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - async_net

  # consumer:
  #   build:
  #     context: .
  #   volumes:
  #     - .:/src
  #   depends_on:
  #     - "rabbitmq"
  #   command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node ~/consumer.js'
  #   environment:
  #     AMQP_URL: amqp://guest:guest@rabbitmq:5672
  #   networks:
  #     - async_net        

networks:
  async_net:
    driver: bridge